[project]
name = "multi-rate-mpc-env"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "win-64"]
preview = ["pixi-build"]

[activation.env]
CMAKE_INSTALL_PREFIX = "$CONDA_PREFIX"

[target.win-64.activation.env]
CMAKE_INSTALL_PREFIX = "%CONDA_PREFIX%\\Library"

[dependencies]
cxx-compiler = "*"
cmake = "*"
make = "*"
ninja = "*"
pkg-config = "*"
yarp = "*"
bipedal-locomotion-framework = "*"
mujoco-python = ">=3.3.2,<4"
idyntree = "*"
osqp-eigen = "*"
pybind11 = "*"
pytorch = "*"
resolve-robotics-uri-py = "*"
scipy = "*"
toml = "*"
hdf5storage = "*"
# Workaround until https://github.com/conda-forge/staged-recipes/pull/30690 is merged
ironcub-models = { git = "https://github.com/ami-iit/ironcub-models.git", tag = "v0.0.2" }

[pypi-dependencies]
mujoco_lib= { path = "./src/mujoco_lib" }

[target.osx-arm64.dependencies]
ncurses = "*"

[tasks]
configure = "cmake -S . -B build -GNinja -DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX"
build = { cmd = "cmake --build build", depends-on = ["configure"] }
install = { cmd = "cmake --install build", depends-on = ["build"] }
simple-example = { cmd = "mpc-simple-example", depends-on = ["install"] }
run-simulation = { cmd = "python src/apps/data_fused_mpc.py", depends-on = ["install"] }

[target.osx-arm64.tasks]
run-simulation = { cmd = "mjpython src/apps/data_fused_mpc.py", depends-on = ["install"] }
