robotPortName = "icubSim"

axesList = [
    "torso_pitch",
    "torso_roll",
    "torso_yaw",
    "l_shoulder_pitch",
    "l_shoulder_roll",
    "l_shoulder_yaw",
    "l_elbow",
    "r_shoulder_pitch",
    "r_shoulder_roll",
    "r_shoulder_yaw",
    "r_elbow",
    "l_hip_pitch",
    "l_hip_roll",
    "l_hip_yaw",
    "l_knee",
    "l_ankle_pitch",
    "l_ankle_roll",
    "r_hip_pitch",
    "r_hip_roll",
    "r_hip_yaw",
    "r_knee",
    "r_ankle_pitch",
    "r_ankle_roll",
]

jetsList = [
    "l_arm_jet_turbine", "r_arm_jet_turbine",
    "chest_l_jet_turbine", "chest_r_jet_turbine"
]

controlBoardsNames = [
    "torso", "left_arm", "right_arm",
    "left_leg", "right_leg"
]

gravity = [0.0, 0.0, -9.81]
CoMOffset = [0.0, 0.0, 0.0]
thresholdNormalForceRobotOnTheGround = 5.0
readZMPFromEstimator = true

[ROBOT_COMMON]
baseFrame = "chest"
